# Generated by Django 3.2.25 on 2024-03-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Active',
            new_name='is_active',
        ),
    ]
